小程序添加解密加密数据方法。
node-webot/co-wechat-api pull request #133
Opened 2020-12-07 14:43 UTC by salamander-mh

add decrypt data function for miniprogram.

2020-12-09 03:21 UTC, JacksonTian commented on lib/api_miniprogram_login.js
> +exports.decryptDataForMiniProgram = async function (sessionKey, iv, encryptedData) {
1. 这是一个同步方法
2. 这是一个实例无关的方法

建议放到 util 文件中。

2020-12-09 03:21 UTC, JacksonTian requested changes
参见评论

2020-12-09 03:30 UTC, salamander-mh commented on lib/api_miniprogram_login.js
> +exports.decryptDataForMiniProgram = async function (sessionKey, iv, encryptedData) {
好的，我改动下。

2020-12-09 14:01 UTC, closed without merging

2020-12-28 06:26 UTC, salamander-mh commented on lib/api_miniprogram_login.js
> +exports.decryptDataForMiniProgram = async function (sessionKey, iv, encryptedData) {
新的pr咋一直没有合并呢？